apiVersion: v1
kind: Service
metadata: 
  name: db
spec:
  selector:
    app: mysql
  ports:
  - protocol: "TCP"
    port: 3306
    targetPort: 3306
  # clusterIP: None
  # type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldb
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: sqlcontainer
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: MYSQL_ALLOW_EMPTY_PASSWORD
        - name: MYSQL_DATABASE
          value: forge
        - name: MYSQL_USER
          value: forge
        - name: MYSQL_PASSWORD
          value: forge