apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: local
spec:
  capacity: 
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: storageclass
  local:
    path: /newmnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - carthage.pride.improwised.dev
 