apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  volumeName: pv
  storageClassName: storageclass
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  